name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ITCH_USERNAME: dasheck
  ITCH_GAME_ID: fantasy-matching-card-game

jobs:
  build-and-deploy:
    name: Build game and upload to Itch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm i --legacy-peer-deps
      - name: Build
        run: npm run build:production
      - name: Get package.json version
        run: echo "PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')" >> $GITHUB_ENV
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./dist
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: html5
          buildNumber: ${{ env.PACKAGE_VERSION }}
